[build]
  # Perintah untuk mem-build project React Anda (Vite menggunakan "npm run build")
  command = "npm run build"
  
  # Folder output hasil build (Vite menggunakan "dist")
  publish = "dist"
  
  # Folder tempat Anda menyimpan fungsi serverless
  functions = "netlify/functions"

[functions]
  directory = "netlify/functions"

# Ini adalah bagian "ajaib" yang menghubungkan frontend dan backend
[[redirects]]
  # Semua permintaan dari frontend Anda yang dimulai dengan /api/...
  from = "/api/*"
  
  # Akan diteruskan ke fungsi Netlify yang sesuai
  # /api/lucky -> /.netlify/functions/flip
  to = "/.netlify/functions/:splat"
  
  # Status 200 berarti ini adalah "rewrite" (proxy), bukan redirect 301
  status = 200